# Generated by Django 3.2 on 2021-12-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_product_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
