# Generated by Django 3.2 on 2021-12-26 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_books_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='sku',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
