# Generated by Django 3.2 on 2022-01-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body_one',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='body_two',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='intro',
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default='body', max_length=500),
        ),
    ]
